global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-osisoft-pisystem2aws-connector
  regions:
    - us-east-1
    - us-west-2
    - eu-west-1
  reporting: true
tests:
  pi2aws:
    parameter_input: pi2aws-test.json
    template_file: pi2aws-master.template
    regions:
      - us-west-2
