global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: aws-industrial-time-series-data-connector
  regions:
    - us-east-1
    - us-west-2
    - eu-west-1
  reporting: true
tests:
  test-kinesis:
    parameter_input: connector-test-kinesis.json
    template_file: industrial-data-connector-master.template
    regions:
      - us-east-1
      - us-west-2
      - eu-west-1
